import test from 'node:test';
import {z} from 'zod';
import assert from 'node:assert/strict';
import {canonicalUrl,consultedUrls,enforceEvidence,runResearch,unknownReport,vettedLedger,jsonSchema} from '../lib/research';
import {reportSchema} from '../lib/report';
import {sample} from '../lib/sample';
const domains=[{domain:'docs.slack.dev',reason:'Official Slack developer documentation.'}];
const entries=sample.report.sources.map((s,i)=>({name:i===0?sample.report.endpoints[0].name:i===1?'user_change':'OAuth',kind:(i===0?'endpoint':i===1?'webhook':'authentication') as 'endpoint'|'webhook'|'authentication',status:'confirmed' as const,fact:'Official evidence for fixture testing',sourceUrl:canonicalUrl(s.url),excerpt:'This is a fixture excerpt only.'}));
const ledger={entries,unknowns:[]};
const provider=(data:unknown,urls:string[]=[])=>new Response(JSON.stringify({status:'completed',output:[{type:'web_search_call',action:{sources:urls.map(url=>({url}))}},{type:'message',content:[{type:'output_text',text:JSON.stringify(data)}]}]}),{status:200});
test('reject unsafe URLs and unrelated citation sources',()=>{assert.equal(canonicalUrl('javascript:alert(1)'),'');assert.equal(canonicalUrl('https://user:password@example.com'),'');assert.equal(canonicalUrl('http://localhost/a'),'');assert.equal(canonicalUrl('https://docs.slack.dev:8443/a'),'');const raw={entries:[...entries,{...entries[0],sourceUrl:'https://docs.slack.dev.evil.example/docs'}],unknowns:[]};const urls=new Set(raw.entries.map(e=>e.sourceUrl));assert.equal(vettedLedger(raw,urls,['docs.slack.dev']).entries.length,3);assert.equal(vettedLedger(raw,new Set(),['docs.slack.dev']).entries.length,0)});
test('trust gate removes invented endpoints and downgrades overall assessment',()=>{const r=structuredClone(sample.report);r.endpoints[0].name='GET /imaginary-employees';const out=enforceEvidence(r,ledger,domains);assert.equal(out.endpoints.length,0);assert.equal(out.verdict,'Insufficient information');assert.equal(out.confidence,'Low')});
test('a fabricated citation cannot support a confirmed claim',()=>{const r=structuredClone(sample.report);r.capabilities[0].sources=[999];const out=enforceEvidence(r,ledger,domains);assert.equal(out.capabilities[0].status,'unknown');assert.equal(out.capabilities[0].sources.length,0);assert.equal(out.feasibility,'Unknown')});
test('positive evidence cannot be used to assert unsupported',()=>{const r=structuredClone(sample.report);r.capabilities[0].status='unsupported';const out=enforceEvidence(r,ledger,domains);assert.equal(out.capabilities[0].status,'unknown')});
test('missing evidence stays unknown, never low or no API',()=>{const r=unknownReport();assert.equal(r.feasibility,'Unknown');assert.equal(r.availability.category,'Unable to determine');assert.ok(reportSchema.safeParse(r).success)});
test('high feasibility requires every listed requirement to be confirmed',()=>{const r=structuredClone(sample.report);r.feasibility='High';r.verdict='Likely feasible';const out=enforceEvidence(r,ledger,domains);assert.equal(out.feasibility,'Medium');assert.equal(out.verdict,'Partially feasible')});
test('sample schema valid and a stable API JSON schema can be produced',()=>{assert.ok(reportSchema.safeParse(sample.report).success);assert.equal(jsonSchema(reportSchema).additionalProperties,false)});
test('untrusted strings in model text are not considered consulted URLs',()=>{assert.equal(consultedUrls({output:[{type:'message',content:[{type:'output_text',text:'https://fake.example'}]}]}).size,0)});
test('dedicated partner research restricts vendor domains and excludes the key from prompt content',async()=>{const calls:Record<string,unknown>[]=[];const queue=[provider({ambiguous:false,vendors:[{...domains[0],ownershipEvidenceUrl:sample.report.sources[0].url}]},[sample.report.sources[0].url]),provider(ledger,sample.report.sources.map(s=>s.url)),provider({entries:[],unknowns:['Partner access not confirmed']}),provider(sample.report)];const fetcher:typeof fetch=async (url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');const body=JSON.parse(String(options?.body));assert.ok(!String(body.input).includes('sk-fixture'));assert.equal(body.store,false);calls.push(body);return queue.shift()!};const stages:string[]=[];const report=await runResearch({product:'Slack',useCase:sample.useCase},'sk-fixture',new AbortController().signal,s=>stages.push(s),fetcher);assert.equal(report.verdict,'Partially feasible');assert.equal(calls.length,4);assert.equal(stages.length,4);assert.deepEqual((calls[1].tools as Array<{filters:unknown}>)[0].filters,{allowed_domains:['docs.slack.dev']});assert.deepEqual((calls[2].tools as Array<{filters:unknown}>)[0].filters,{allowed_domains:['docs.slack.dev']});assert.equal(calls[2].tool_choice,'required');assert.match(String(calls[2].input),/technology \/ integration \/ ISV/);assert.equal(calls[3].tools,undefined)});
test('provider authentication error is actionable and never returned as a report',async()=>{await assert.rejects(runResearch({product:'Slack',useCase:sample.useCase},'sk-fixture',new AbortController().signal,()=>{},async()=>new Response('',{status:401})),/temporarily unavailable/)});
test('malformed provider response fails closed',async()=>{await assert.rejects(runResearch({product:'Slack',useCase:sample.useCase},'sk-fixture',new AbortController().signal,()=>{},async()=>provider({foo:'bar'})),/validation/)});
test('ambiguous vendor stops research without inventing sources',async()=>{let calls=0;const report=await runResearch({product:'Ambiguous',useCase:sample.useCase},'sk-fixture',new AbortController().signal,()=>{},async()=>{calls++;return provider({ambiguous:true,vendors:[]})});assert.equal(calls,1);assert.equal(report.sources.length,0);assert.equal(report.verdict,'Insufficient information')});

test('provider schema preserves validation bounds',()=>{assert.deepEqual(jsonSchema(z.string().min(1).max(250)),{type:'string',minLength:1,maxLength:250});assert.deepEqual(jsonSchema(z.array(z.string()).min(1).max(5)),{type:'array',items:{type:'string'},minItems:1,maxItems:5});});

test('native feature evidence without an API operation cannot establish feasibility',()=>{const r=structuredClone(sample.report);r.endpoints=[];const out=enforceEvidence(r,{entries:entries.filter(e=>e.kind!=='endpoint'),unknowns:[]},domains);assert.equal(out.feasibility,'Unknown');assert.ok(out.capabilities.every(c=>c.status!=='confirmed'));});
test('unverified developer resource names are removed',()=>{const r=structuredClone(sample.report);r.resources=[{name:'Invented developer community',kind:'community',text:'Join here.',status:'confirmed',sources:[1]}];assert.equal(enforceEvidence(r,ledger,domains).resources.length,0);});

test('public API evidence cannot confirm free developer access or marketplace eligibility',()=>{const r=structuredClone(sample.report);r.partnerAccess.fees={text:'Free for everyone',status:'confirmed',sources:[1]};r.partnerAccess.listing_requirements={text:'Anyone can list',status:'confirmed',sources:[1]};const out=enforceEvidence(r,ledger,domains);assert.equal(out.partnerAccess.fees.status,'unknown');assert.equal(out.partnerAccess.listing_requirements.status,'unknown');assert.equal(out.feasibility,'Medium');});
test('partner requirements preserve correctly typed official evidence',()=>{const r=structuredClone(sample.report);r.partnerAccess.fees={text:'Developer access requires a paid plan.',status:'confirmed',sources:[1]};const out=enforceEvidence(r,{entries:[...entries,{...entries[0],kind:'fees',fact:'Developer access requires a paid plan.'}],unknowns:[]},domains);assert.equal(out.partnerAccess.fees.status,'confirmed');});
