'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleHelp, FileSearch, Fingerprint, Link2, Loader2, LockKeyhole, ShieldCheck, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { sample } from '@/lib/sample';
import type { Assessment, Claim, Report } from '@/lib/report';
const examples = [{product:'Workday',useCase:'Import employees with name, email, department, manager, employment status, and automatically synchronize changes.'},{product:'HubSpot',useCase:'Create contacts from our application and synchronize updates in both directions.'}];
export default function Home(){
 const [product,setProduct]=useState(''); const [useCase,setUseCase]=useState(''); const [result,setResult]=useState<Assessment|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [phase,setPhase]=useState('');
 const controller=useRef<AbortController|null>(null); const reportRef=useRef<HTMLElement>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 const current=useRef({busy,result}); current.current={busy,result};
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'stage_integration_brief',description:'Fill the integration brief for review. Does not start paid research.',inputSchema:{type:'object',properties:{product:{type:'string'},useCase:{type:'string'}},required:['product','useCase'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const x=input as {product?:unknown;useCase?:unknown};if(current.current.busy)throw new Error('Research is running.');if(!x||typeof x.product!=='string'||!x.product.trim()||x.product.length>120||typeof x.useCase!=='string'||x.useCase.trim().length<15||x.useCase.length>2500)throw new Error('Provide a product and a 15–2500 character use case.');const p=x.product.trim(),u=x.useCase.trim();flushSync(()=>{setProduct(p);setUseCase(u);setError('')});return {staged:true,product:p,useCase:u};}});
  register({name:'read_feasibility_assessment',description:'Read the report currently displayed, including its sample label and source links.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({assessment:current.current.result,researching:current.current.busy})});
  return ()=>lifecycle.abort();
 },[]);
 async function research(e:React.FormEvent){e.preventDefault(); if(!product.trim()||useCase.trim().length<15){setError('Add a product and describe the integration in at least 15 characters.');return;}
 setBusy(true);setError('');setResult(null);if(window.innerWidth<760)setTimeout(()=>reportRef.current?.scrollIntoView({behavior:'smooth'}),50);setPhase('Locating official documentation'); const abort=new AbortController();controller.current=abort;
 try {const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product:product.trim(),useCase:useCase.trim()}),signal:abort.signal});
 if(!response.ok){const d=await response.json() as {error?:string};throw new Error(d.error||'Research could not be completed. Please try again.');}
 const reader=response.body!.getReader();const decoder=new TextDecoder();let buffer='';let completed=false;
 while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==='status')setPhase(event.message);if(event.type==='error')throw new Error(event.message);if(event.type==='result'){setResult(event.data);completed=true;}}}
 if(!completed)throw new Error('The research connection ended before a report was ready. Please retry.');
 }catch(err){if(abort.signal.aborted)setError('Research canceled. You can revise the brief and try again.');else setError(err instanceof Error?err.message:'Research failed. Please try again.');}finally{setBusy(false);controller.current=null;}}
 const showSample=()=>{setResult(sample);setError('');if(window.innerWidth<850)setTimeout(()=>reportRef.current?.scrollIntoView({behavior:'smooth'}),50)};
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/" aria-label="IntegrationIQ home"><span className="brand-mark"><img src="/favicon.svg" width="44" height="44" alt=""/></span>Integration<span className="brand-iq">IQ</span></a><span className="workspace-label">AI-powered research to assess your next product integration</span></header>
 <main className="workspace"><aside className="brief-panel"><div className="eyebrow"><span className="tiny-line"/> 01 / START HERE</div><h1>Can our product<br/> connect with theirs?</h1><p className="intro">Tell us what you want to build. We’ll check the vendor’s API documentation for evidence.</p>
 <form onSubmit={research}><label htmlFor="product">Product to integrate with</label><Input id="product" placeholder="e.g. Workday" maxLength={120} value={product} onChange={e=>setProduct(e.target.value)} disabled={busy} required className="brief-input"/>
 <div className="label-row"><label htmlFor="usecase">What should the integration do?</label></div><Textarea id="usecase" placeholder="Describe the data you need, where it should go, and what should happen when it changes…" value={useCase} onChange={e=>setUseCase(e.target.value)} maxLength={2500} minLength={15} required disabled={busy} className="brief-textarea"/><div className="field-help">Describe what your customers should be able to do.</div>
 <Button className="research-button" type="submit" disabled={busy}>{busy?<Loader2 className="spin"/>:<FileSearch size={18}/>} {busy?'Researching…':'Assess feasibility'}{!busy&&<ArrowRight className="push-right"/>}</Button>
 {busy&&<Button type="button" variant="ghost" onClick={()=>controller.current?.abort()} className="cancel-button">Cancel research</Button>}
 {error&&<p role="alert" className="error-message">{error}</p>}
 </form><div className="examples"><span>Try a brief</span>{examples.map(e=><Button variant="outline" key={e.product} disabled={busy} onClick={()=>{setProduct(e.product);setUseCase(e.useCase);setError('')}}>{e.product}<ArrowUpRight size={13}/></Button>)}</div>
 <div className="trust-note"><ShieldCheck size={20}/><div><strong>Evidence over assumptions</strong><p>Verified claims have sources. Gaps stay unknown. No code or effort estimates.</p></div></div>
 <div className="brief-footer"><span>INTEGRATIONIQ / V1</span><span>Built for the before-build decision.</span></div>
 </aside><section ref={reportRef} className="report-panel" aria-label="Feasibility assessment" aria-busy={busy}>
 <div className="report-toolbar"><div><FileSearch size={16}/><span>Feasibility report</span></div><span>{result?.sample?'REFERENCE EXAMPLE':result?'RESEARCH COMPLETE':'EVIDENCE FIRST'}</span></div>
 {busy?<div className="loading-state" role="status"><div className="research-orbit"><FileSearch size={35}/></div><p className="eyebrow">RESEARCH IN PROGRESS</p><h2>{phase}</h2><p>Checking public vendor sources for <strong>{product}</strong>.<br/>This can take a few minutes.</p><div className="loading-line"/><p className="small-muted">Unverified information will be marked unknown.</p></div>:result?<ReportView data={result}/>:<div className="empty-state"><div className="empty-symbol"><FileSearch size={38} strokeWidth={1.3}/><span className="symbol-badge"><Check size={15}/></span></div><p className="eyebrow">02 / YOUR ASSESSMENT</p><h2>An integration decision.<br/><span>Backed by API evidence.</span></h2><p>A short answer to “Can our product build this?”<br className="desktop-break"/> with the documentation to support your next conversation.</p><div className="report-preview-list"><div><ShieldCheck/><span><strong>Can we build it?</strong> API support for your specific use case.</span></div><div><Link2/><span><strong>Which operations?</strong> Relevant endpoints and HTTP methods.</span></div><div><LockKeyhole/><span><strong>What access do we need?</strong> Accounts, approvals, keys or tokens.</span></div><div><BookOpen/><span><strong>Where’s the evidence?</strong> API docs, developer resources and integration examples.</span></div></div><Button variant="outline" className="sample-button" onClick={showSample}>Explore a sample report<ArrowRight size={16}/></Button><span className="sample-caption">Slack member directory · Reviewed 14 Sep 2026</span></div>}
 </section></main></div>
}
function Sources({ids,report}:{ids:number[],report:Report}){return <>{ids.map(id=>{const source=report.sources.find(s=>s.id===id);return source?<a className="citation" key={id} href={source.url} title={source.title} target="_blank" rel="noreferrer" aria-label={`Source ${id}: ${source.title}`}>{id}</a>:null})}</>}
function Status({status}:{status:Claim['status']}){return <span className={`status status-${status}`}>{status==='confirmed'?<Check/>:status==='unsupported'?<X/>:<CircleHelp/>}{status==='confirmed'?'Confirmed':status==='unknown'?'Unverified':'Unavailable'}</span>}
function ReportView({data}:{data:Assessment}){const r=data.report;const count=r.capabilities.filter(c=>c.status==='confirmed').length;
 return <article className="report-content">{data.sample&&<div className="sample-banner"><BookOpen size={16}/><span>Sample report · Fixed example, not a live assessment of your brief.</span></div>}<div className="report-heading"><div><p className="eyebrow">PARTNER FEASIBILITY BRIEF</p><h2>{data.product}</h2></div><span className="review-date">{new Date(data.researchedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span></div><p className="assessed-brief">{data.useCase}</p>
 <div className={`verdict-card level-${r.feasibility.toLowerCase()}`}><div className="verdict-top"><span className="eyebrow">CAN WE BUILD THIS?</span><span className="score">{r.feasibility==='Unknown'?'Not rated':r.feasibility}</span></div><h3>{r.verdict}</h3><p>{r.summary.text}<Sources ids={r.summary.sources} report={r}/></p></div>
 <section className="report-section"><div className="section-title"><h3>Does the API support our use case?</h3><span>{count} / {r.capabilities.length} confirmed</span></div><div className="capabilities">{r.capabilities.map((c,i)=><div className="capability-row" key={i}><div><h4>{c.name}</h4><p>{c.text}<Sources ids={c.sources} report={r}/></p></div><Status status={c.status}/></div>)}</div><p className="legend">Confirmed = supported by documentation · Unverified = still needs an answer · Unavailable = explicitly ruled out</p></section>
 <section className="report-section"><h3>API operations for your use case</h3><p>These are the documented ways your product could interact with {data.product}.</p>{r.endpoints.length?r.endpoints.map((c,i)=><div className="endpoint" key={i}><code>{c.name}</code><p>{c.text}<Sources ids={c.sources} report={r}/></p></div>):<p>Unverified — no relevant API operation was confirmed. Native product features alone do not establish integration support.</p>}</section>
 <section className="report-section access-summary"><h3>What access would we need?</h3><p><strong>{r.availability.category}</strong> · {r.availability.evidence.text}<Sources ids={r.availability.evidence.sources} report={r}/></p>{[r.access,r.authentication].map((c,i)=><p key={i}>{c.status==='unknown'?'Unverified: ':''}{c.text}<Sources ids={c.sources} report={r}/></p>)}</section>
 <div className="confidence-box"><CircleHelp/><div><h4>Before you commit</h4><p>{r.nextStep}</p><span className="small-muted">{r.confidence} confidence in the available evidence</span></div></div>
 <details className="technical-evidence"><summary>Limits & synchronization<span>Open for remaining gaps, change notifications and confidence details</span></summary><p className="assessed-brief">Requested direction: {r.direction.replaceAll('Product',data.product)}</p><ul className="risk-list">{r.risks.map((c,i)=><li key={i}>{c.status==='unknown'?'Unverified: ':''}{c.text}<Sources ids={c.sources} report={r}/></li>)}</ul><section className="report-section"><h3>Change notifications</h3>{r.webhooks.length?r.webhooks.map((c,i)=><div className="event-item" key={i}><h4>{c.name} <Status status={c.status}/></h4><p>{c.text}<Sources ids={c.sources} report={r}/></p></div>):<p>Relevant events were not verified.</p>}</section><p className="assessed-brief">{r.confidenceExplanation}</p></details>
 <details className="technical-evidence"><summary>Developer resources & examples<span>Accounts, communities and existing integrations</span></summary>{(['developer_account','community','integration_example'] as const).map(kind=><section className="report-section" key={kind}><h3>{kind==='developer_account'?'Developer account or sandbox':kind==='community'?'Developer community':'Existing integration examples'}</h3>{r.resources.filter(x=>x.kind===kind).length?r.resources.filter(x=>x.kind===kind).map((x,i)=><p key={i}><strong>{x.name}</strong> · {x.text}<Sources ids={x.sources} report={r}/></p>):<p>Not verified in the resources reviewed.</p>}</section>)}<p className="report-disclaimer">Existing integrations are useful context. They do not prove that the same API access is available to your company.</p></details>
 <details className="technical-evidence source-section"><summary>Documentation reviewed<span>{r.sources.length} official sources · open the original evidence</span></summary><section className="report-section"><div className="section-title"><h3>Sources & documentation</h3><span>{r.sources.length} official sources</span></div>{r.sources.map(s=><a className="source-row" href={s.url} key={s.id} target="_blank" rel="noreferrer"><span className="source-number">{s.id}</span><div><strong>{s.title}</strong><p>{new URL(s.url).hostname} · {s.officialReason}</p></div><ArrowUpRight size={16}/></a>)}{!r.sources.length&&<p>No official sources were verified.</p>}</section></details><p className="report-disclaimer">A documentation-based assessment, not a tested integration. Unknown does not mean impossible.</p></article>
}
